// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClccXJowrsl2mO5BTmniErWKFf_WmmWCE',
    appId: '1:1016171859830:web:aa8dc18df7bd3652d2f457',
    messagingSenderId: '1016171859830',
    projectId: 'login-flutter-a5ee3',
    authDomain: 'login-flutter-a5ee3.firebaseapp.com',
    storageBucket: 'login-flutter-a5ee3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArDlgF_SJvWnzr3fra9r_3dmq8jGJku80',
    appId: '1:1016171859830:android:4314acfaa2916ecdd2f457',
    messagingSenderId: '1016171859830',
    projectId: 'login-flutter-a5ee3',
    storageBucket: 'login-flutter-a5ee3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6mFUM7UsadHPQI_S1rnuXpfksocJOQm8',
    appId: '1:1016171859830:ios:6b6711773ee2afa5d2f457',
    messagingSenderId: '1016171859830',
    projectId: 'login-flutter-a5ee3',
    storageBucket: 'login-flutter-a5ee3.appspot.com',
    iosBundleId: 'com.example.loginfirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6mFUM7UsadHPQI_S1rnuXpfksocJOQm8',
    appId: '1:1016171859830:ios:0d7c256beaa44d5ed2f457',
    messagingSenderId: '1016171859830',
    projectId: 'login-flutter-a5ee3',
    storageBucket: 'login-flutter-a5ee3.appspot.com',
    iosBundleId: 'com.example.loginfirebase.RunnerTests',
  );
}
